### ISSUE TITLE
Failed to get the current sub/segment from the context. at Object.contextMissingLogError

### ISSUE THREAD

**Issue by elribonazo** [unbill/mongoose-xray#1]
Error: Failed to get the current sub/segment from the context. at Object.contextMissingLogError [as contextMissing] (/var/app/current/node_modules/aws-xray-sdk-core/lib/context_utils.js:26:19) at Object.getSegment (/var/app/current/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45) at Object.exports.createQuerySubsegment (/var/app/current/node_modules/mongoose-xray/lib/query-middleware.js:59:26) at model.Query.<anonymous> (/var/app/current/node_modules/mongoose-xray/lib/query-middleware.js:31:34) at callMiddlewareFunction (/var/app/current/node_modules/kareem/index.js:474:23) at next (/var/app/current/node_modules/kareem/index.js:58:7) at next (/var/app/current/node_modules/kareem/index.js:81:9) at Kareem.execPre (/var/app/current/node_modules/kareem/index.js:86:8) at Kareem.wrap (/var/app/current/node_modules/kareem/index.js:265:8) at model.Query._findOne (/var/app/current/node_modules/kareem/index.js:375:11) at model.Query.Query.findOne (/var/app/current/node_modules/mongoose/lib/query.js:2078:8) at _hooks.execPre (/var/app/current/node_modules/mongoose/lib/query.js:4089:21) at /var/app/current/node_modules/kareem/index.js:23:7 at ZoneDelegate.invokeTask (/var/app/current/node_modules/zone.js/dist/zone-node.js:423:31) at Zone.runTask (/var/app/current/node_modules/zone.js/dist/zone-node.js:195:47) at ZoneTask.invokeTask (/var/app/current/node_modules/zone.js/dist/zone-node.js:498:34) at ZoneTask.invoke (/var/app/current/node_modules/zone.js/dist/zone-node.js:487:48) at data.args.(anonymous function) (/var/app/current/node_modules/zone.js/dist/zone-node.js:1421:25) at _combinedTickCallback (internal/process/next_tick.js:132:7) at process._tickDomainCallback (internal/process/next_tick.js:219:9)

# Description of the issue:
We are completely stuck without segment, so nothing works. Crashes the server is we don't add that env setting to just log it.

No queries are logged, nothing in x-ray (elastic beanstalk)

# Explanation:
Having a default xray configuration with Elastic Beanstalk and mongoose-xray with default settings, it does not matter verbose value.

Package JSON
        "mongoose": "5.4.21",
        "mongoose-xray": "^3.0.2",
        "aws-sdk": "^2.443.0",
        "aws-xray-sdk": "^3.0.1",

Instead of instantiating a Schema, we have created a base Mongoose Model that we use everywhere.
```javascript
const path = require('path');
const mongoose = require('mongoose');
const e = require('../../../error');

class Model extends mongoose.model {

    constructor(obj) {
        if (!obj.schema) {
            throw new Error("Please specify a schema when initialising a model");
        }
        if (!obj.name) {
            throw new Error("Please specify the model name when initialising a model");
        }

        const { schema, name } = obj;
        const baseSchema = new mongoose.Schema(schema);
        if (obj.hooks && Array.isArray(obj.hooks)) {
            obj.hooks.forEach((hook) => {
                baseSchema[hook.lifeCycle](hook.name, hook.method);
            });
        }

        if (mongoose.models && mongoose.models[name]) {
            super(name);
        } else {
            super(name, baseSchema);
            if (obj.methods && typeof obj.methods === "object") {
                const methodNames = Object.keys(obj.methods);
                for (let i = 0; i < methodNames.length; i++) {
                    const methodName = methodNames[i];
                    this[methodName] = obj.methods[methodName].bind(this);
                }
            }
        }
    }

}


module.exports = (collection) => {
    const model = new Model({
        name: collection,
        schema: {
            wpId: {
                type: Number
            },
            slug: {
                type: String,
                unique: function () {
                    return this.slug !== "";
                },
                required: function () {
                    return this.status !== "draft" && this.status !== 'auto-draft' && this.status !== 'trash';
                }
            },
     }
    });

    return model;
}

module.exports = Model;
```

It does not matter if I require the plugin before mongodb is connected or not.... and this is how we setup express and AWSXRay

```javascript
  AWSXRay.enableAutomaticMode();
            AWSXRay.config([AWSXRay.plugins.EC2Plugin, AWSXRay.plugins.ElasticBeanstalkPlugin]);
            app.use(AWSXRay.express.openSegment(`Whatever_${process.env.NODE_ENV}`));
            mongoose.plugin(require('mongoose-xray'), { verbose: false });
//Winston logger
 AWSXRay.setLogger(logger);
```

Also the last express middleware is 
```javascript
  app.use(AWSXRay.express.closeSegment());
```

Thanks a lot in advance

**Comment by eric-swann-q2** [comment]
@elribonazo 
I have not tried it with the express middleware, but it works fine for our project with the hapi plugin.  Is it possible to set up a very minimal reproduction? 
The short of it is that the mongoose middleware just asks AWSXray for the open segment using the normal mechanism:

```
const AWSXRay = require('aws-xray-sdk-core');
const parent = AWSXRay.getSegment();
```
 In this case AWSXRay.getSegement() is throwing because it does not believe a parent segment is available.  The parent segment should be created by the express middleware.

If you just run the same code sample above in some random handler in your express app, is it able to retrieve the segment or does it throw?

**Comment by elribonazo** [comment]
Hi @eric-swann-q2, here my answers

**I have not tried it with the express middleware, but it works fine for our project with the hapi plugin. Is it possible to set up a very minimal reproduction?**

yes, sure.


If you just run the same code sample above in some random handler in your express app, is it able to retrieve the segment or does it throw?

No it does not, i have just tried the following:
```javascript
        AWSXRay.getSegment().setUser(user.id);

```
and yeah, getSegment returns undefined.

This means the express middleware is not creating the segment, correct? The express thing seems to be working though... I mean its reporting the api traces.

**Comment by elribonazo** [comment]
Hello @eric-swann-q2 , I got the DEMO Ready in this link 

[https://github.com/elribonazo/mongoose-xray-issue](url)

# mongoose-xray-issue
Reproduction project to help debugging a bug on Mongoose-xray
In order to reproduce run

1. docker-compose -f "docker-compose.yml" up -d --build
2. node index

**Comment by eric-swann-q2** [comment]
OK @elribonazo I'll take a look in just a bit and see if I can repro it.  
You said:
`This means the express middleware is not creating the segment, correct? The express thing seems to be working though... I mean its reporting the api traces.`

I guess the answer is that although it may be creating the segment, it is somehow just getting lost/dropped at some point.

Even if I can repro it, not sure I have any ideas on how to remedy the situation if the context is just randomly losing the segment.  

Just out of curiosity, have you tried either the mysql or postgres extensions?

**Comment by elribonazo** [comment]
I have been able to make it work by hacking the code a little. It does not work 100% of times, because we sometimes call Models outside Express Routes...

```javascript
/**
 * Creates the subsegment for query middleware
 * @param operation {String} The operation that is to occur (findOne, update, etc...)
 * @param query {Object} The mongoose query
 * @param [options] {MongooseXRayOptions} Options for XRay recording
 */
exports.createQuerySubsegment = (operation, query, options) => {
  const parent = AWSXRay.getSegment();
  if (parent) {
    const subsegment = parent.addNewSubsegment(
      `${query.model.modelName}-${operation}`
    );
    subsegment.addAnnotation('model', query.model.modelName);
    subsegment.addMetadata('operation', operation);
    if (options && options.verbose) {
      subsegment.addMetadata('filter', query.getQuery());
      subsegment.addMetadata('update', query.getUpdate());
      subsegment.addMetadata('options', query.getOptions());
      subsegment.addMetadata('populatedPaths', query.getPopulatedPaths());
    }
    logDebugSafe(
      `Mongoose-XRay: Opened Subsegment: ${subsegment.id} Parent Segment: ${parent.id}`
    );
    return subsegment;
  } else {

    var segment = new AWSXRay.Segment("SAMESEGMENT_IN_EXPRESS_MW");
    const subsegment = segment.addNewSubsegment(
      `${query.model.modelName}-${operation}`
    );
    subsegment.addAnnotation('model', query.model.modelName);
    subsegment.addMetadata('operation', operation);
    if (options && options.verbose) {
      subsegment.addMetadata('filter', query.getQuery());
      subsegment.addMetadata('update', query.getUpdate());
      subsegment.addMetadata('options', query.getOptions());
      subsegment.addMetadata('populatedPaths', query.getPopulatedPaths());
    }
    logDebugSafe(
      `Mongoose-XRay: Opened Subsegment: ${subsegment.id} Parent Segment: ${segment.id}`
    );
    return subsegment;
  }
};

```

By the way i don't know why i don't have query.getFilters in my query instance... I always have it undefined so I'm using query.getQuery.

**Comment by eric-swann-q2** [comment]
@elribonazo Yes, if you call models outside of express routes, it will fail.  In this case, you can either add your own code to create a segment (like you did above) or handle the situation (ignore it or do whatever):
`AWSXRay.setContextMissingStrategy(() => {});`
or have it log errors instead of throwing:
```
Environment variables:
AWS_XRAY_CONTEXT_MISSING – Set to LOG_ERROR to avoid throwing exceptions when your instrumented code attempts to record data when no segment is open.
RUNTIME_ERROR – Throw a runtime exception (default).
LOG_ERROR – Log an error and continue.
```

Creating your own segment on the fly may work, but it concerns me if that happens while you are in an express route which should already have the parent segment available.

**Comment by elribonazo** [comment]
@eric-swann-q2 the subsegments aparently appear inside the main segment.

**Comment by elribonazo** [comment]
I'm closing the issue as the module is working perfect.

The problem is express xray middleware... When I run a Query outside a Route, but for example, inside a middleware it will not find the segment.
