### ISSUE TITLE
Contribute to aws-xray-sdk-node?

### ISSUE THREAD

**Issue by joebowbeer** [unbill/mongoose-xray#4]
In case you weren't aware, AWS now offers to host and publish user contributed middleware:

https://github.com/aws/aws-xray-sdk-node#community-contributions-for-new-middleware

The readme says web framework; but mongoose middleware may be welcome?

**Comment by eric-swann-q2** [comment]
Hey @joebowbeer I'm in discussions with the AWS folks to get this done...but I plan on getting the Koa support in first.

**Comment by eric-swann-q2** [comment]
After the difficult experience adding in Hapi and Koa, I'm gonna keep this project independent.
