### ISSUE TITLE
Avoid mongo operation to fail

### ISSUE THREAD

**Issue by marcioviegas** [unbill/mongoose-xray#7]
Should we wrapper the plugin to avoid an error that would explode the operation/query? Just wondering.

**Comment by eric-swann-q2** [comment]
Hey @marcioviegas can you be more specific?  Are you concerned that a failure in the middleware would interfere with Mongo?  I haven't encountered this myself, but I suppose it's always possible.

**Comment by eric-swann-q2** [comment]
Oi @marcioviegas, can you respond to the question above?

**Comment by marcioviegas** [comment]
So basically I was afraid of using this plugin because if something failed during the open/close segments the actual query to the database would fail and that would put my whole service down.

**Comment by eric-swann-q2** [comment]
That should not be the case, the error handling built into the underling xray mechanisms will not prevent the query from running if something fails in the open/close.
